on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/553fa7c211857afef4b0efe5ec31fdab
          gist_title: Pr치ctica 4 - Contador Binario MPLAB X PIC assembler MPASM PIC18F4550
          gist_description: Pr치cticas MPASM
          github_file: Proyecto/PIC18F4550/Contador_Binario.X/contador_binario.asm
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/a0386c9ab234889f279d9f2cc1433953
          gist_title: Pr치ctica 4 - Contador Binario MPLAB X PIC assembler MPASM PIC18F45K50
          gist_description: Pr치cticas MPASM
          github_file: Proyecto/PIC18F45K50/Contador_Binario.X/contador_binario.asm
          file_encoding: ISO-8859-1